package cmd

import (
	"bytes"
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/aldinokemal/go-whatsapp-web-multidevice/pkg/baileysimport"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"go.mau.fi/whatsmeow/types"
)

// Synthetic fixture generated by pkg/baileysimport/testdata/gen.
var importFixture = filepath.Join("..", "pkg", "baileysimport", "testdata", "bob_auth.json")

func TestImportBaileysSkipsAppInit(t *testing.T) {
	assert.True(t, commandSkipsAppInit([]string{"import-baileys", "--input", "x.json"}))
	assert.False(t, commandSkipsAppInit([]string{"rest"}))
	assert.False(t, commandSkipsAppInit(nil))
}

func TestImportBaileysDryRunWritesNothing(t *testing.T) {
	dir := t.TempDir()
	dbPath := filepath.Join(dir, "whatsapp.db")
	var out bytes.Buffer
	err := runImportBaileys(context.Background(), &out, importFixture, importBaileysRun{dbURI: "file:" + dbPath, dryRun: true})
	require.NoError(t, err)
	assert.Contains(t, out.String(), "device:                  5511900000001:7@s.whatsapp.net")
	assert.Contains(t, out.String(), "pre-keys:                27 (17 uploaded)")
	assert.Contains(t, out.String(), "signal sessions:         3 (+1 previous states)")
	assert.Contains(t, out.String(), "dry run")
	_, statErr := os.Stat(dbPath)
	assert.True(t, os.IsNotExist(statErr), "dry run must not create the store")
	assertNoKeyMaterial(t, out.String())
}

func TestImportBaileysWritesAndRefusesDuplicates(t *testing.T) {
	ctx := context.Background()
	dir := t.TempDir()
	run := importBaileysRun{dbURI: "file:" + filepath.Join(dir, "whatsapp.db")}

	var out bytes.Buffer
	require.NoError(t, runImportBaileys(ctx, &out, importFixture, run))
	assert.Contains(t, out.String(), "imported 5511900000001:7@s.whatsapp.net")
	assertNoKeyMaterial(t, out.String())

	err := runImportBaileys(ctx, &bytes.Buffer{}, importFixture, run)
	require.ErrorIs(t, err, baileysimport.ErrDeviceExists)
	assert.Contains(t, err.Error(), "--replace")

	run.replace = true
	run.skipSignalSessions = true
	require.NoError(t, runImportBaileys(ctx, &bytes.Buffer{}, importFixture, run))

	store, err := openImportStore(ctx, run.dbURI)
	require.NoError(t, err)
	defer store.Close()
	jid := types.NewADJID("5511900000001", 0, 7)
	dev, err := store.Container.GetDevice(ctx, jid)
	require.NoError(t, err)
	require.NotNil(t, dev)
	has, err := dev.Sessions.HasSession(ctx, "5511900000002:3")
	require.NoError(t, err)
	assert.False(t, has, "--replace --skip-signal-sessions must leave no old sessions behind")
}

func TestImportBaileysSeparateKeysStore(t *testing.T) {
	ctx := context.Background()
	dir := t.TempDir()
	run := importBaileysRun{
		dbURI:   "file:" + filepath.Join(dir, "whatsapp.db"),
		keysURI: "file:" + filepath.Join(dir, "whatsapp-keys.db"),
	}
	require.NoError(t, runImportBaileys(ctx, &bytes.Buffer{}, importFixture, run))
	keys, err := openImportStore(ctx, run.keysURI)
	require.NoError(t, err)
	defer keys.Close()
	dev, err := keys.Container.GetDevice(ctx, types.NewADJID("5511900000001", 0, 7))
	require.NoError(t, err)
	require.NotNil(t, dev)
	has, err := dev.Sessions.HasSession(ctx, "5511900000002:3")
	require.NoError(t, err)
	assert.True(t, has)
}

func TestImportBaileysRejectsBadInput(t *testing.T) {
	dir := t.TempDir()
	bad := filepath.Join(dir, "bad.json")
	require.NoError(t, os.WriteFile(bad, []byte(`{"creds":{"registrationId":1},"keys":{}}`), 0o600))
	err := runImportBaileys(context.Background(), &bytes.Buffer{}, bad, importBaileysRun{dbURI: "file:" + filepath.Join(dir, "w.db")})
	require.ErrorIs(t, err, baileysimport.ErrNotPaired)
	err = runImportBaileys(context.Background(), &bytes.Buffer{}, filepath.Join(dir, "missing.json"), importBaileysRun{dryRun: true})
	require.Error(t, err)
}

// assertNoKeyMaterial checks that no private key from the fixture is printed.
func assertNoKeyMaterial(t *testing.T, output string) {
	t.Helper()
	raw, err := os.ReadFile(importFixture)
	require.NoError(t, err)
	var dump struct {
		Creds struct {
			NoiseKey struct {
				Private struct {
					Data string `json:"data"`
				} `json:"private"`
			} `json:"noiseKey"`
			SignedIdentityKey struct {
				Private struct {
					Data string `json:"data"`
				} `json:"private"`
			} `json:"signedIdentityKey"`
			AdvSecretKey string `json:"advSecretKey"`
		} `json:"creds"`
	}
	require.NoError(t, json.Unmarshal(raw, &dump))
	for _, secret := range []string{dump.Creds.NoiseKey.Private.Data, dump.Creds.SignedIdentityKey.Private.Data, dump.Creds.AdvSecretKey} {
		require.NotEmpty(t, secret)
		assert.False(t, strings.Contains(output, secret), "output leaks key material")
	}
}
