package baileysimport

import (
	"bytes"
	"context"
	"database/sql"
	"encoding/base64"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"go.mau.fi/libsignal/groups"
	"go.mau.fi/libsignal/protocol"
	"go.mau.fi/libsignal/session"
	"go.mau.fi/whatsmeow/store"
	"go.mau.fi/whatsmeow/types"

	"github.com/aldinokemal/go-whatsapp-web-multidevice/pkg/sqlite"
)

// The fixtures in testdata are produced by testdata/gen/gen_fixtures.mjs with
// the real libsignal-node and Baileys group code. They are synthetic: every
// key was generated by the script.

type fixtureMessage struct {
	From      string `json:"from"`
	To        string `json:"to"`
	Sender    string `json:"sender"`
	Type      string `json:"type"`
	Body      string `json:"body"`
	Plaintext string `json:"plaintext"`
}

func (m fixtureMessage) bytes(t *testing.T) []byte {
	t.Helper()
	b, err := base64.StdEncoding.DecodeString(m.Body)
	if err != nil {
		t.Fatalf("fixture body: %v", err)
	}
	return b
}

type fixtureVectors struct {
	Bob struct {
		JID     string `json:"jid"`
		LID     string `json:"lid"`
		Address string `json:"address"`
	} `json:"bob"`
	Alice struct {
		JID     string `json:"jid"`
		Address string `json:"address"`
	} `json:"alice"`
	Pairwise    []fixtureMessage `json:"pairwise"`
	Reply       fixtureMessage   `json:"reply"`
	PrekeyReply fixtureMessage   `json:"prekeyReply"`
	Group       struct {
		ID        string           `json:"id"`
		OwnSender string           `json:"ownSender"`
		Pending   []fixtureMessage `json:"pending"`
	} `json:"group"`
	AppStateKeyIDs []string `json:"appStateKeyIds"`
}

func loadVectors(t *testing.T) fixtureVectors {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join("testdata", "vectors.json"))
	if err != nil {
		t.Fatal(err)
	}
	var v fixtureVectors
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatal(err)
	}
	return v
}

func loadPlan(t *testing.T, name string, opts Options) *Plan {
	t.Helper()
	f, err := os.Open(filepath.Join("testdata", name))
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	state, err := Parse(f)
	if err != nil {
		t.Fatalf("parse %s: %v", name, err)
	}
	plan, err := Convert(state, opts)
	if err != nil {
		t.Fatalf("convert %s: %v", name, err)
	}
	return plan
}

func openTestStore(t *testing.T) *Store {
	t.Helper()
	uri := sqlite.FormatChatStorageURI("file:"+filepath.Join(t.TempDir(), "whatsapp.db"), true, true)
	db, err := sql.Open(sqlite.DriverName, uri)
	if err != nil {
		t.Fatal(err)
	}
	s, err := NewStore(context.Background(), db, sqlite.DriverName, nil)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = s.Close() })
	return s
}

func importFixture(t *testing.T, name string) (*Store, *store.Device) {
	t.Helper()
	ctx := context.Background()
	plan := loadPlan(t, name, Options{})
	target := openTestStore(t)
	if err := Write(ctx, target, plan, WriteOptions{}); err != nil {
		t.Fatalf("write %s: %v", name, err)
	}
	dev, err := target.Container.GetDevice(ctx, plan.Device.ID)
	if err != nil || dev == nil {
		t.Fatalf("imported device not found: %v", err)
	}
	return target, dev
}

func signalAddress(t *testing.T, addr string) *protocol.SignalAddress {
	t.Helper()
	jid, err := types.ParseJID(addr + "@x")
	if err != nil {
		t.Fatalf("address %q: %v", addr, err)
	}
	return protocol.NewSignalAddress(jid.User, uint32(jid.Device))
}

func newCipher(dev *store.Device, addr *protocol.SignalAddress) *session.Cipher {
	builder := session.NewBuilderFromSignal(dev, addr, store.SignalProtobufSerializer)
	return session.NewCipher(builder, addr)
}

func decryptPairwise(t *testing.T, dev *store.Device, msg fixtureMessage) string {
	t.Helper()
	ctx := context.Background()
	ser := store.SignalProtobufSerializer
	addr := signalAddress(t, msg.From)
	cipher := newCipher(dev, addr)
	var plaintext []byte
	var err error
	if msg.Type == "pkmsg" {
		var pk *protocol.PreKeySignalMessage
		pk, err = protocol.NewPreKeySignalMessageFromBytes(msg.bytes(t), ser.PreKeySignalMessage, ser.SignalMessage)
		if err == nil {
			plaintext, err = cipher.DecryptMessage(ctx, pk)
		}
	} else {
		var m *protocol.SignalMessage
		m, err = protocol.NewSignalMessageFromBytes(msg.bytes(t), ser.SignalMessage)
		if err == nil {
			plaintext, err = cipher.Decrypt(ctx, m)
		}
	}
	if err != nil {
		t.Fatalf("decrypt %s from %s: %v", msg.Plaintext, msg.From, err)
	}
	return string(plaintext)
}

// TestRoundTripSignalSessions imports Bob's Baileys state and proves, with
// go.mau.fi/libsignal alone, that the converted sessions are the same
// sessions libsignal-node holds:
//   - encrypting the next reply yields byte-for-byte the ciphertext
//     libsignal-node produced from the same state (and that Alice's
//     libsignal-node accepted in the generator);
//   - the same holds for a session Bob initiated that still carries a
//     pending pre-key (the reply must again be a pkmsg);
//   - every message Alice, Carol and Eve sent but Bob never read decrypts:
//     a stored message key on a closed chain, a stored key on the current
//     chain, a message on a chain Bob never saw (ratchet step), a message
//     from the future on an old chain, a pkmsg that consumes an imported
//     one-time pre-key, and a message addressed to a closed (previous)
//     session.
func TestRoundTripSignalSessions(t *testing.T) {
	ctx := context.Background()
	v := loadVectors(t)
	_, bob := importFixture(t, "bob_auth.json")
	ser := store.SignalProtobufSerializer

	// Deterministic reply on the current sending chain.
	alice := signalAddress(t, v.Reply.To)
	reply, err := newCipher(bob, alice).Encrypt(ctx, []byte(v.Reply.Plaintext))
	if err != nil {
		t.Fatalf("encrypt reply: %v", err)
	}
	if reply.Type() != protocol.WHISPER_TYPE || v.Reply.Type != "msg" {
		t.Fatalf("reply type = %d (fixture %s), want whisper message", reply.Type(), v.Reply.Type)
	}
	if !bytes.Equal(reply.Serialize(), v.Reply.bytes(t)) {
		t.Fatalf("reply ciphertext differs from libsignal-node's\n go:   %x\n node: %x", reply.Serialize(), v.Reply.bytes(t))
	}

	// Deterministic reply on a session with a pending pre-key.
	dave := signalAddress(t, v.PrekeyReply.To)
	pkReply, err := newCipher(bob, dave).Encrypt(ctx, []byte(v.PrekeyReply.Plaintext))
	if err != nil {
		t.Fatalf("encrypt prekey reply: %v", err)
	}
	if pkReply.Type() != protocol.PREKEY_TYPE || v.PrekeyReply.Type != "pkmsg" {
		t.Fatalf("prekey reply type = %d (fixture %s), want pkmsg", pkReply.Type(), v.PrekeyReply.Type)
	}
	assertSamePreKeyMessage(t, pkReply.Serialize(), v.PrekeyReply.bytes(t))

	// Pending messages, in the fixture order.
	for _, msg := range v.Pairwise {
		if got := decryptPairwise(t, bob, msg); got != msg.Plaintext {
			t.Fatalf("decrypted %q, want %q", got, msg.Plaintext)
		}
	}
	// Carol's pkmsg consumed imported one-time pre-key 5.
	if pk, err := bob.PreKeys.GetPreKey(ctx, 5); err != nil || pk != nil {
		t.Fatalf("pre-key 5 should have been consumed, got %v, %v", pk, err)
	}
	// Decrypting twice must fail (message keys are one-shot on both sides).
	replayed, err := protocol.NewSignalMessageFromBytes(v.Pairwise[1].bytes(t), ser.SignalMessage)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := newCipher(bob, alice).Decrypt(ctx, replayed); err == nil {
		t.Fatal("replayed message decrypted twice")
	}

	// Alice's own Baileys state, converted the same way, reads both the reply
	// that matched libsignal-node and a new one sent after Bob's ratchet step.
	after, err := newCipher(bob, alice).Encrypt(ctx, []byte("r2"))
	if err != nil {
		t.Fatalf("encrypt after ratchet: %v", err)
	}
	_, aliceDev := importFixture(t, "alice_auth.json")
	bobAddr := signalAddress(t, v.Bob.Address)
	for _, tc := range []struct {
		body []byte
		want string
	}{{reply.Serialize(), "r1"}, {after.Serialize(), "r2"}} {
		m, err := protocol.NewSignalMessageFromBytes(tc.body, ser.SignalMessage)
		if err != nil {
			t.Fatal(err)
		}
		got, err := newCipher(aliceDev, bobAddr).Decrypt(ctx, m)
		if err != nil {
			t.Fatalf("alice decrypt %s: %v", tc.want, err)
		}
		if string(got) != tc.want {
			t.Fatalf("alice decrypted %q, want %q", got, tc.want)
		}
	}
}

func assertSamePreKeyMessage(t *testing.T, got, want []byte) {
	t.Helper()
	ser := store.SignalProtobufSerializer
	g, err := protocol.NewPreKeySignalMessageFromBytes(got, ser.PreKeySignalMessage, ser.SignalMessage)
	if err != nil {
		t.Fatalf("parse go pkmsg: %v", err)
	}
	w, err := protocol.NewPreKeySignalMessageFromBytes(want, ser.PreKeySignalMessage, ser.SignalMessage)
	if err != nil {
		t.Fatalf("parse node pkmsg: %v", err)
	}
	switch {
	case g.RegistrationID() != w.RegistrationID():
		t.Fatalf("registration id %d, want %d", g.RegistrationID(), w.RegistrationID())
	case g.SignedPreKeyID() != w.SignedPreKeyID():
		t.Fatalf("signed pre-key id %d, want %d", g.SignedPreKeyID(), w.SignedPreKeyID())
	case *g.PreKeyID() != *w.PreKeyID():
		t.Fatalf("pre-key id %+v, want %+v", *g.PreKeyID(), *w.PreKeyID())
	case !bytes.Equal(g.BaseKey().Serialize(), w.BaseKey().Serialize()):
		t.Fatal("base key differs")
	case !bytes.Equal(g.IdentityKey().Serialize(), w.IdentityKey().Serialize()):
		t.Fatal("identity key differs")
	case !bytes.Equal(g.WhisperMessage().Serialize(), w.WhisperMessage().Serialize()):
		t.Fatalf("inner message differs\n go:   %x\n node: %x", g.WhisperMessage().Serialize(), w.WhisperMessage().Serialize())
	}
}

// TestRoundTripSenderKeys decrypts group messages Alice sent with Baileys'
// GroupCipher (a stored message key, a future iteration and a message under
// a rotated key), then encrypts with Bob's imported own sender key and checks
// that Alice's imported copy of that key reads it.
func TestRoundTripSenderKeys(t *testing.T) {
	ctx := context.Background()
	v := loadVectors(t)
	_, bob := importFixture(t, "bob_auth.json")
	ser := store.SignalProtobufSerializer

	for _, msg := range v.Group.Pending {
		name := protocol.NewSenderKeyName(v.Group.ID, signalAddress(t, msg.Sender))
		cipher := groups.NewGroupCipher(groups.NewGroupSessionBuilder(bob, ser), name, bob)
		m, err := protocol.NewSenderKeyMessageFromBytes(msg.bytes(t), ser.SenderKeyMessage)
		if err != nil {
			t.Fatal(err)
		}
		got, err := cipher.Decrypt(ctx, m)
		if err != nil {
			t.Fatalf("group decrypt %s: %v", msg.Plaintext, err)
		}
		if string(got) != msg.Plaintext {
			t.Fatalf("group decrypted %q, want %q", got, msg.Plaintext)
		}
	}

	own := protocol.NewSenderKeyName(v.Group.ID, signalAddress(t, v.Group.OwnSender))
	encrypted, err := groups.NewGroupCipher(groups.NewGroupSessionBuilder(bob, ser), own, bob).Encrypt(ctx, []byte("o3"))
	if err != nil {
		t.Fatalf("group encrypt: %v", err)
	}
	_, aliceDev := importFixture(t, "alice_auth.json")
	m, err := protocol.NewSenderKeyMessageFromBytes(encrypted.SignedSerialize(), ser.SenderKeyMessage)
	if err != nil {
		t.Fatal(err)
	}
	got, err := groups.NewGroupCipher(groups.NewGroupSessionBuilder(aliceDev, ser), own, aliceDev).Decrypt(ctx, m)
	if err != nil {
		t.Fatalf("alice group decrypt: %v", err)
	}
	if string(got) != "o3" {
		t.Fatalf("alice group decrypted %q, want o3", got)
	}
}

// TestImportFixtureContents checks the non-Signal parts of the import.
func TestImportFixtureContents(t *testing.T) {
	ctx := context.Background()
	v := loadVectors(t)
	plan := loadPlan(t, "bob_auth.json", Options{})
	s := plan.Summary()
	checks := map[string][2]int{
		"pre_keys":            {s.PreKeys, 27},
		"pre_keys_uploaded":   {s.PreKeysUploaded, 17},
		"sessions":            {s.Sessions, 3},
		"previous_states":     {s.PreviousSessionStates, 1},
		"identity_keys":       {s.IdentityKeys, 3},
		"sender_keys":         {s.SenderKeys, 2},
		"app_state_sync_keys": {s.AppStateSyncKeys, 2},
		"lid_mappings":        {s.LIDMappings, 2},
		"privacy_tokens":      {s.PrivacyTokens, 1},
		"ignored_versions":    {s.Ignored[KeyTypeAppStateSyncVersion], 1},
		"ignored_devices":     {s.Ignored[KeyTypeDeviceList], 1},
		"ignored_memory":      {s.Ignored[KeyTypeSenderKeyMemory], 1},
		"skipped_tctoken":     {s.Skipped["tctoken without timestamp"], 1},
	}
	for name, c := range checks {
		if c[0] != c[1] {
			t.Errorf("%s = %d, want %d", name, c[0], c[1])
		}
	}
	if s.JID != v.Bob.JID || s.LID != v.Bob.LID {
		t.Errorf("summary jid/lid = %s/%s, want %s/%s", s.JID, s.LID, v.Bob.JID, v.Bob.LID)
	}
	summaryJSON, _ := json.Marshal(s)
	for _, k := range plan.PreKeys {
		if bytes.Contains(summaryJSON, []byte(base64.StdEncoding.EncodeToString(k.Private[:]))) {
			t.Fatal("summary leaks key material")
		}
	}

	target := openTestStore(t)
	if err := Write(ctx, target, plan, WriteOptions{}); err != nil {
		t.Fatal(err)
	}
	dev, err := target.Container.GetDevice(ctx, plan.Device.ID)
	if err != nil || dev == nil {
		t.Fatalf("device: %v", err)
	}
	if dev.PushName != "Bob Import" || dev.Platform != "android" || dev.LID.String() != v.Bob.LID {
		t.Errorf("device fields: push=%q platform=%q lid=%s", dev.PushName, dev.Platform, dev.LID)
	}
	if n, err := dev.PreKeys.UploadedPreKeyCount(ctx); err != nil || n != 17 {
		t.Errorf("uploaded pre-keys = %d, %v; want 17", n, err)
	}
	for _, idB64 := range v.AppStateKeyIDs {
		id, _ := base64.StdEncoding.DecodeString(idB64)
		key, err := dev.AppStateKeys.GetAppStateSyncKey(ctx, id)
		if err != nil || key == nil || len(key.Data) != 32 || len(key.Fingerprint) == 0 {
			t.Errorf("app state key %s: %+v, %v", idB64, key, err)
		}
	}
	if key, _ := dev.AppStateKeys.GetAppStateSyncKey(ctx, mustB64(t, v.AppStateKeyIDs[0])); key != nil && key.Timestamp != 1758000000123 {
		t.Errorf("Long timestamp decoded as %d", key.Timestamp)
	}
	lid, err := dev.LIDs.GetLIDForPN(ctx, types.NewJID("5511900000005", types.DefaultUserServer))
	if err != nil || lid.User != "300000000000005" {
		t.Errorf("reverse-only lid mapping: %v, %v", lid, err)
	}
	token, err := dev.PrivacyTokens.GetPrivacyToken(ctx, types.NewJID("100000000000002", types.HiddenUserServer))
	if err != nil || token == nil || token.Timestamp.Unix() != 1758000000 || len(token.Token) != 16 {
		t.Errorf("privacy token: %+v, %v", token, err)
	}
	for _, addr := range []string{"5511900000002:3", "5511900000004:0", "300000000000005_1:0"} {
		if ok, err := dev.Sessions.HasSession(ctx, addr); err != nil || !ok {
			t.Errorf("session %s missing: %v", addr, err)
		}
	}

	// A second import of the same JID is refused unless Replace is set.
	if err := Write(ctx, target, plan, WriteOptions{}); err == nil {
		t.Fatal("second import without Replace succeeded")
	}
	if err := Write(ctx, target, plan, WriteOptions{Replace: true}); err != nil {
		t.Fatalf("replace: %v", err)
	}
}

// TestWriteToSeparateKeysStore mirrors GOWA's --db-keys-uri layout.
func TestWriteToSeparateKeysStore(t *testing.T) {
	ctx := context.Background()
	plan := loadPlan(t, "bob_auth.json", Options{})
	primary, keysStore := openTestStore(t), openTestStore(t)
	if err := Write(ctx, primary, plan, WriteOptions{Keys: keysStore}); err != nil {
		t.Fatal(err)
	}
	for name, s := range map[string]*Store{"primary": primary, "keys": keysStore} {
		dev, err := s.Container.GetDevice(ctx, plan.Device.ID)
		if err != nil || dev == nil {
			t.Fatalf("%s device: %v", name, err)
		}
		has, _ := dev.Sessions.HasSession(ctx, "5511900000002:3")
		if has != (name == "keys") {
			t.Errorf("%s store has session = %v", name, has)
		}
	}
}

// TestSkipSignalSessions leaves sessions and identities out.
func TestSkipSignalSessions(t *testing.T) {
	plan := loadPlan(t, "bob_auth.json", Options{SkipSignalSessions: true})
	if len(plan.Sessions) != 0 || len(plan.Identities) != 0 || plan.Ignored[KeyTypeSession] != 3 {
		t.Fatalf("sessions=%d identities=%d ignored=%d", len(plan.Sessions), len(plan.Identities), plan.Ignored[KeyTypeSession])
	}
	if len(plan.SenderKeys) != 2 || len(plan.PreKeys) != 27 {
		t.Fatalf("sender keys=%d pre-keys=%d", len(plan.SenderKeys), len(plan.PreKeys))
	}
}

func mustB64(t *testing.T, s string) []byte {
	t.Helper()
	b, err := base64.StdEncoding.DecodeString(s)
	if err != nil {
		t.Fatal(err)
	}
	return b
}
